### ISSUE TITLE
Error calling REST service with Mendix 8

### ISSUE THREAD

**Issue by lordlothar99** [shelterbox/countrycodes#1]
When using Mendix 8, there's an error on loading, cause some keys are null in the ws response

```
An error has occurred while handling the request. [User 'administrator' with session id '5ce46a6b-XXXX-XXXX-XXXX-XXXXXXXX6322' and roles 'Administrator']

--------

com.mendix.modules.microflowengine.MicroflowException: Error calling REST service
	at DataHubIo_CountryCodes.ACT_CountryCodes_Update (CallRest : 'Call REST (GET)')

Advanced stacktrace:
	at com.mendix.integration.actions.microflow.RestCallAction.execute(RestCallAction.scala:59)

Caused by: com.mendix.systemwideinterfaces.MendixRuntimeException: Error while importing, key value for 'ISO3166_1_Alpha_2' should not be null.
	at com.mendix.integration.importer.handlers.ObjectFinder.$anonfun$createArgs$1(ObjectFinder.scala:108)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.immutable.Map$Map2.foreach(Map.scala:159)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at com.mendix.integration.importer.handlers.ObjectFinder.createArgs(ObjectFinder.scala:100)
	at com.mendix.integration.importer.handlers.ObjectFinder.findInDatabaseInternal(ObjectFinder.scala:65)
	at com.mendix.integration.importer.handlers.ObjectFinder.findInDatabase(ObjectFinder.scala:55)
	at com.mendix.integration.importer.handlers.ObjectFinder.$anonfun$find$1(ObjectFinder.scala:24)
	at scala.Option.orElse(Option.scala:447)
	at com.mendix.integration.importer.handlers.ObjectFinder.find(ObjectFinder.scala:24)
	at com.mendix.integration.importer.handlers.ObjectMappingHandler.findObject(ObjectMappingHandler.scala:278)
	at com.mendix.integration.importer.handlers.ObjectMappingHandler.getObjectViaDefaultAction(ObjectMappingHandler.scala:238)
	at com.mendix.integration.importer.handlers.ObjectMappingHandler.getObjectImportInfo(ObjectMappingHandler.scala:107)
	at com.mendix.integration.importer.handlers.ObjectMappingHandler.createObjectInfo(ObjectMappingHandler.scala:126)
	at com.mendix.integration.importer.handlers.ObjectMappingHandler.$anonfun$endObjectElement$1(ObjectMappingHandler.scala:84)
	at scala.Option.map(Option.scala:230)
	at com.mendix.integration.importer.handlers.ObjectMappingHandler.endObjectElement(ObjectMappingHandler.scala:79)
	at com.mendix.integration.importer.handlers.StreamingHandler.$anonfun$handleElement$1(StreamingHandler.scala:82)
	at com.mendix.integration.importer.handlers.StreamingHandler.$anonfun$handleElement$1$adapted(StreamingHandler.scala:80)
	at scala.Option.foreach(Option.scala:407)
	at com.mendix.integration.importer.handlers.StreamingHandler.handleElement(StreamingHandler.scala:80)
	at com.mendix.integration.importer.handlers.StreamingHandler.endObject(StreamingHandler.scala:70)
	at com.mendix.integration.importer.json.JsonStreamingHandler.endElement(JsonStreamingHandler.scala:114)
	at com.mendix.integration.importer.json.JsonStreamingHandler.parseObject(JsonStreamingHandler.scala:60)
	at com.mendix.integration.importer.json.JsonStreamingHandler.parseFullArray(JsonStreamingHandler.scala:92)
	at com.mendix.integration.importer.json.JsonStreamingHandler.parseArray(JsonStreamingHandler.scala:65)
	at com.mendix.integration.importer.json.JsonStreamingHandler.$anonfun$parse$1(JsonStreamingHandler.scala:37)
	at com.mendix.integration.util.AutoCloseableUtil$.using(AutoCloseableUtil.scala:10)
	at com.mendix.integration.importer.json.JsonStreamingHandler.parse(JsonStreamingHandler.scala:30)
	at com.mendix.integration.importer.json.JsonImporter.$anonfun$parseJson$3(JsonImporter.scala:50)
	at scala.util.Try$.apply(Try.scala:213)
	at com.mendix.integration.importer.json.JsonImporter.$anonfun$parseJson$2(JsonImporter.scala:50)
	at com.mendix.integration.util.AutoCloseableUtil$.using(AutoCloseableUtil.scala:10)
	at com.mendix.integration.importer.json.JsonImporter.$anonfun$parseJson$1(JsonImporter.scala:49)
	at com.mendix.integration.util.AutoCloseableUtil$.using(AutoCloseableUtil.scala:10)
	at com.mendix.integration.importer.json.JsonImporter.parseJson(JsonImporter.scala:48)
	at com.mendix.integration.importer.json.JsonImporter.parse$1(JsonImporter.scala:37)
	at com.mendix.integration.importer.json.JsonImporter.$anonfun$importStream$1(JsonImporter.scala:39)
	at com.mendix.integration.util.ContextUtil$RichContext$.withTransaction$extension(ContextUtil.scala:11)
	at com.mendix.integration.importer.json.JsonImporter.importStream(JsonImporter.scala:39)
	at com.mendix.integration.internal.InternalIntegration.doImportStream(InternalIntegration.scala:98)
	at com.mendix.integration.internal.InternalIntegration.doImportStream$(InternalIntegration.scala:86)
	at com.mendix.integration.internal.InternalIntegrationImpl.doImportStream(InternalIntegrationImpl.scala:38)
	at com.mendix.integration.actions.ImportMappingResult$.apply(ImportMappingResult.scala:60)
	at com.mendix.integration.actions.ServiceCallResult$.importResponse$1(ServiceCallResult.scala:51)
	at com.mendix.integration.actions.ServiceCallResult$.apply(ServiceCallResult.scala:56)
	at com.mendix.integration.actions.microflow.RestCallAction.handleResponse(RestCallAction.scala:80)
	at com.mendix.integration.actions.microflow.RestCallAction.$anonfun$execute$2(RestCallAction.scala:55)
	at com.mendix.integration.util.AutoCloseableUtil$.using(AutoCloseableUtil.scala:10)
	at com.mendix.integration.actions.microflow.RestCallAction.execute(RestCallAction.scala:54)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowObject.execute(MicroflowObject.java:47)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAfterBreakingIfNecessary(MicroflowImpl.java:215)
	at com.mendix.modules.microflowengine.microflow.impl.MicroflowImpl.executeAction(MicroflowImpl.java:165)
	at com.mendix.systemwideinterfaces.core.UserAction.execute(UserAction.java:46)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.doCall(CoreActionHandlerImpl.scala:71)
	at com.mendix.basis.actionmanagement.CoreActionHandlerImpl.call(CoreActionHandlerImpl.scala:49)
	at com.mendix.core.actionmanagement.CoreAction.call(CoreAction.java:54)
	at com.mendix.basis.actionmanagement.ActionManagerBase$1.execute(ActionManagerBase.java:147)
	at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:32)
	at com.mendix.basis.actionmanagement.ActionManagerBase.executeSync(ActionManagerBase.java:152)
	at com.mendix.basis.actionmanagement.MicroflowCallBuilderImpl.execute(MicroflowCallBuilderImpl.scala:32)
	at com.mendix.webui.actions.client.ExecuteMicroflowAction.runMicroflow(ExecuteMicroflowAction.scala:76)
	at com.mendix.webui.actions.client.ExecuteMicroflowAction.$anonfun$apply$3(ExecuteMicroflowAction.scala:42)
	at com.mendix.webui.actions.client.RegularClientAction$Helpers$.$anonfun$liftEither$1(RegularClientAction.scala:29)
	at com.mendix.webui.actions.client.RegularClientAction$Helpers$StateHandler.$anonfun$apply$4(RegularClientAction.scala:55)
	at com.mendix.webui.requesthandling.helpers.StateHandling.withState(StateHandling.scala:35)
	at com.mendix.webui.requesthandling.helpers.StateHandling.withState$(StateHandling.scala:32)
	at com.mendix.webui.actions.client.RegularClientAction$Helpers$StateHandler.withState(RegularClientAction.scala:45)
	at com.mendix.webui.actions.client.RegularClientAction$Helpers$StateHandler.apply(RegularClientAction.scala:53)
	at com.mendix.webui.actions.client.RegularClientAction$Helpers$StateHandler.apply(RegularClientAction.scala:45)
	at com.mendix.webui.actions.client.ExecuteMicroflowAction.apply(ExecuteMicroflowAction.scala:43)
	at com.mendix.webui.actions.client.ExecuteMicroflowAction.apply(ExecuteMicroflowAction.scala:22)
	at com.mendix.webui.actions.client.RegularClientAction.$anonfun$execute$3(RegularClientAction.scala:109)
	at scala.util.Try$.apply(Try.scala:213)
	at com.mendix.webui.actions.client.RegularClientAction.$anonfun$execute$2(RegularClientAction.scala:109)
	at com.mendix.webui.actions.client.RegularClientAction.$anonfun$execute$2$adapted(RegularClientAction.scala:107)
	at com.mendix.webui.requesthandling.helpers.ContextHandling.$anonfun$inContext$5(ContextHandling.scala:47)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.mendix.basis.actionmanagement.IMonitoredAction$$anon$1.execute(IMonitoredAction.scala:47)
	at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:32)
	at com.mendix.basis.actionmanagement.IMonitoredAction.monitor(IMonitoredAction.scala:49)
	at com.mendix.basis.actionmanagement.IMonitoredAction.monitor$(IMonitoredAction.scala:25)
	at com.mendix.webui.requesthandling.helpers.ContextHandling$ClientMonitoredAction.monitor(ContextHandling.scala:59)
	at com.mendix.webui.requesthandling.helpers.ContextHandling.inContext(ContextHandling.scala:47)
	at com.mendix.webui.requesthandling.helpers.ContextHandling.inContext$(ContextHandling.scala:27)
	at com.mendix.webui.actions.client.RegularClientAction.inContext(RegularClientAction.scala:86)
	at com.mendix.webui.requesthandling.helpers.ContextHandling.inContext(ContextHandling.scala:24)
	at com.mendix.webui.requesthandling.helpers.ContextHandling.inContext$(ContextHandling.scala:19)
	at com.mendix.webui.actions.client.RegularClientAction.inContext(RegularClientAction.scala:86)
	at com.mendix.webui.actions.client.RegularClientAction.$anonfun$execute$1(RegularClientAction.scala:107)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.mendix.webui.requesthandling.helpers.ProfileHandling.profileRequest(ProfileHandling.scala:14)
	at com.mendix.webui.requesthandling.helpers.ProfileHandling.profileRequest$(ProfileHandling.scala:10)
	at com.mendix.webui.actions.client.RegularClientAction.profileRequest(RegularClientAction.scala:86)
	at com.mendix.webui.actions.client.RegularClientAction.execute(RegularClientAction.scala:104)
	at com.mendix.webui.requesthandling.ClientRequestHandler.handleAction(ClientRequestHandler.scala:104)
	at com.mendix.webui.requesthandling.ClientRequestHandler.processRequest(ClientRequestHandler.scala:81)
	at com.mendix.externalinterface.connector.RequestHandler.doProcessRequest(RequestHandler.java:40)
	at com.mendix.external.connector.MxRuntimeConnector$1.execute(MxRuntimeConnector.java:76)
	at com.mendix.external.connector.MxRuntimeConnector$1.execute(MxRuntimeConnector.java:73)
	at com.mendix.util.classloading.Runner.doRunUsingClassLoaderOf(Runner.java:32)
	at com.mendix.external.connector.MxRuntimeConnector.processRequest(MxRuntimeConnector.java:79)
	at com.mendix.basis.impl.MxRuntimeImpl.processRequest(MxRuntimeImpl.java:937)
	at com.mendix.m2ee.appcontainer.server.handler.RuntimeHandler.service(RuntimeHandler.java:42)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:867)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:502)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Gustav-Coleske** [comment]
Looks like the value in the JSON dataset for Sark is null for the key fields.  I was hoping that using the M49 field as the key instead of ISO3166_1_Alpha_2 and ISO3166_1_Alpha_3 will work, but no luck.  For Taiwan, the M49 is showing as null.

**Comment by ollyspooner** [comment]
@Gustav-Coleske, unfortunately the dataset is outside my control, so the missing or bad values will have to be fudged somehow.

**Comment by Gustav-Coleske** [comment]
Thank you Olly.  I suppose my comment was more of an FYI for everyone.  For anyone else experiencing the same problem, I ended up just putting a Convert microflow in the JSON mapping to map a null value to something else that is unique.
